# Generated by Django 5.2.4 on 2025-08-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
