# Generated by Django 5.2.4 on 2025-08-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="img",
            field=models.ImageField(upload_to="categories/"),
        ),
    ]
