# Generated by Django 5.2.4 on 2025-08-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0004_alter_categories_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
