# Generated by Django 5.2.4 on 2025-08-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0006_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("review", models.CharField(max_length=500)),
            ],
        ),
    ]
