# Generated by Django 5.2.4 on 2025-08-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0007_testimonials"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonials",
            old_name="review",
            new_name="content",
        ),
    ]
