# Generated by Django 5.2.4 on 2025-08-15 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0008_rename_review_testimonials_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonials",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testimonials",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("discounted_price", models.CharField(max_length=50)),
                ("original_price", models.CharField(max_length=50)),
                ("color_options", models.CharField(max_length=10)),
                ("img", models.ImageField(upload_to="products/")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="furni.categories",
                    ),
                ),
            ],
        ),
    ]
