# Generated by Django 5.2.4 on 2025-08-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0009_testimonials_created_testimonials_updated_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Categorie",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
        migrations.RenameModel(
            old_name="Testimonials",
            new_name="Testimonial",
        ),
    ]
