# Generated by Django 5.2.4 on 2025-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0010_rename_categories_categorie_rename_products_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="assembly",
            field=models.CharField(
                choices=[("Not Required", "Not Required"), ("Required", "Required")],
                default="Not Required",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="customization",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Not Available", "Not Available"),
                ],
                default="Available",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="img2",
            field=models.ImageField(default=2, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="img3",
            field=models.ImageField(default=2, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
