# Generated by Django 5.2.4 on 2025-08-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0011_product_assembly_product_customization_product_img2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(max_length=500),
        ),
    ]
