# Generated by Django 5.2.4 on 2025-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0012_alter_testimonial_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
