# Generated by Django 5.2.4 on 2025-08-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0013_contactform"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactForm",
            new_name="Contact",
        ),
    ]
