# Generated by Django 5.2.4 on 2025-08-16 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0014_rename_contactform_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
