# Generated by Django 5.2.4 on 2025-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0015_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(max_length=200),
        ),
    ]
