# Generated by Django 5.2.4 on 2025-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0016_alter_contact_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.IntegerField(),
        ),
    ]
