# Generated by Django 5.2.4 on 2025-08-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0017_alter_product_options_alter_product_discounted_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
