# Generated by Django 5.2.4 on 2025-08-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0019_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
    ]
