# Generated by Django 5.2.4 on 2025-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0019_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=300)),
                ("street", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=6)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=15)),
            ],
        ),
    ]
