# Generated by Django 5.2.4 on 2025-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0020_deliveryaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="warranty",
            field=models.IntegerField(),
        ),
    ]
