# Generated by Django 5.2.4 on 2025-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0022_deliveryaddress_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
