# Generated by Django 5.2.4 on 2025-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0024_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="products",
            field=models.ManyToManyField(to="furni.cartitem"),
        ),
    ]
