# Generated by Django 5.2.4 on 2025-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0025_orders_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.ManyToManyField(to="furni.deliveryaddress"),
        ),
    ]
