# Generated by Django 5.2.4 on 2025-08-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0026_orders_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="orders",
            name="address",
        ),
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.PROTECT,
                to="furni.deliveryaddress",
            ),
            preserve_default=False,
        ),
    ]
