# Generated by Django 5.2.4 on 2025-08-28 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0027_deliveryaddress_is_deleted_remove_orders_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="products",
        ),
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="furni.deliveryaddress"
            ),
        ),
    ]
