# Generated by Django 5.2.4 on 2025-08-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0031_remove_cartitem_anonymous_remove_cartitem_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="discounted_price",
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
