# Generated by Django 5.2.4 on 2025-08-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0034_remove_cartitem_anonymous_remove_cartitem_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="created",
        ),
    ]
