# Generated by Django 5.2.4 on 2025-09-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0037_orders_anonymous_orders_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="address",
        ),
    ]
