# Generated by Django 5.2.4 on 2025-09-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0038_remove_orders_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.deliveryaddress",
            ),
            preserve_default=False,
        ),
    ]
