# Generated by Django 5.2.4 on 2025-09-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0039_orders_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.deliveryaddress",
            ),
        ),
    ]
