# Generated by Django 5.2.4 on 2025-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0041_alter_orders_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="delivered",
            field=models.DateField(blank=True, null=True),
        ),
    ]
