# Generated by Django 5.2.4 on 2025-09-04 03:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0042_orders_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="order_no",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
