# Generated by Django 5.2.4 on 2025-09-04 03:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0043_orders_order_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_no",
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
