# Generated by Django 5.2.4 on 2025-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0045_alter_orders_order_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="shipped",
            field=models.DateField(blank=True, null=True),
        ),
    ]
