# Generated by Django 5.2.4 on 2025-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0046_orders_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
