# Generated by Django 5.2.4 on 2025-09-09 06:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0047_deliveryaddress_is_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DeliveryAddress",
            new_name="BillingAddress",
        ),
    ]
