# Generated by Django 5.2.4 on 2025-09-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0050_alter_shippingaddress_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address",
            new_name="ship_address",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="city",
            new_name="ship_city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="firstname",
            new_name="ship_firstname",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="lastname",
            new_name="ship_lastname",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="phone",
            new_name="ship_phone",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="pincode",
            new_name="ship_pincode",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="state",
            new_name="ship_state",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="street",
            new_name="ship_street",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="email",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="ship_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
