# Generated by Django 5.2.4 on 2025-09-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0051_rename_address_shippingaddress_ship_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="address",
            new_name="billing_address",
        ),
        migrations.AddField(
            model_name="orders",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.shippingaddress",
            ),
        ),
    ]
