# Generated by Django 5.2.4 on 2025-09-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0052_rename_address_orders_billing_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
