# Generated by Django 5.2.4 on 2025-09-10 15:44

import furni.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0053_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_no",
            field=models.CharField(
                default=furni.models.generate_order_id,
                editable=False,
                max_length=14,
                unique=True,
            ),
        ),
    ]
