# Generated by Django 5.2.4 on 2025-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0054_delete_customuser_alter_orders_order_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="replacement_ordered",
            field=models.BooleanField(default=False),
        ),
    ]
