# Generated by Django 5.2.4 on 2025-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0055_orders_replacement_ordered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="replacement_ordered",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="replacement_ordered",
            field=models.BooleanField(default=False),
        ),
    ]
