# Generated by Django 5.2.4 on 2025-09-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0056_remove_orders_replacement_ordered_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replacements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="furni.orderitem",
                    ),
                ),
            ],
        ),
    ]
