# Generated by Django 5.2.4 on 2025-09-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0057_replacements"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Replacements",
            new_name="Replacement",
        ),
    ]
