# Generated by Django 5.2.4 on 2025-09-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0058_rename_replacements_replacement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Replacement",
        ),
    ]
