# Generated by Django 5.2.4 on 2025-09-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0059_delete_replacement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("picked_up", models.DateField(blank=True, null=True)),
                ("recieved", models.DateField(blank=True, null=True)),
                ("refund_initiated", models.DateField(blank=True, null=True)),
                ("refund_credited", models.DateField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="furni.orderitem",
                    ),
                ),
            ],
        ),
    ]
