# Generated by Django 5.2.4 on 2025-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0060_replacement"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bought by mistake", "Bought by mistake"),
                    ("Better Price available", "Better Price Available"),
                    ("Perfomance or Quality Issue", "Perfomance or Quality Issue"),
                    ("Item arrived too late ", "Item arrived too late"),
                    ("Missing parts or accessories", "Missing parts or accessories"),
                    ("Wrong item was sent", "Wrong item was sent"),
                    ("No longer needed", "No longer needed"),
                    (
                        "Inaccurate website description",
                        "Inaccurate website description",
                    ),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
