# Generated by Django 5.2.4 on 2025-09-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0061_replacement_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="comments",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
