# Generated by Django 5.2.4 on 2025-09-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0063_alter_replacement_comments_alter_replacement_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="individual_order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.orderitem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="replacement",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="furni.orders"
            ),
        ),
    ]
