# Generated by Django 5.2.4 on 2025-09-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0064_replacement_individual_order_alter_replacement_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replacement",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.orders",
            ),
        ),
    ]
