# Generated by Django 5.2.4 on 2025-09-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0065_alter_replacement_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replacement",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.orders",
            ),
            preserve_default=False,
        ),
    ]
