# Generated by Django 5.2.4 on 2025-09-16 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0066_alter_replacement_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="replacement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Bought by mistake", "Bought by mistake"),
                    ("Better Price available", "Better Price Available"),
                    ("Performance or Quality Issue", "Performance or Quality Issue"),
                    ("Item arrived too late", "Item arrived too late"),
                    ("Missing parts or accessories", "Missing parts or accessories"),
                    ("Wrong item was sent", "Wrong item was sent"),
                    ("No longer needed", "No longer needed"),
                    (
                        "Inaccurate website description",
                        "Inaccurate website description",
                    ),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField(max_length=500)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="furni.product"
                    ),
                ),
            ],
        ),
    ]
