# Generated by Django 5.2.4 on 2025-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0067_alter_replacement_reason_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
