# Generated by Django 5.2.4 on 2025-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0068_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="img",
            field=models.ImageField(default=1, upload_to="reviews/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
