# Generated by Django 5.2.4 on 2025-09-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0069_review_img_review_title_alter_review_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
    ]
