# Generated by Django 5.2.4 on 2025-09-18 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0071_review_name_alter_review_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now
            ),
            preserve_default=False,
        ),
    ]
