# Generated by Django 5.2.4 on 2025-09-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0072_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="adhoc_no",
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
