# Generated by Django 5.2.4 on 2025-09-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0073_product_adhoc_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="adhoc_no",
        ),
    ]
