# Generated by Django 5.2.4 on 2025-09-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0074_remove_product_adhoc_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Living Room", "Living Room"),
                    ("Bed Room", "Bed Room"),
                    ("Dining Room", "Dining Room"),
                    ("Home Office", "Home Office"),
                    ("Plastic Chairs", "Plastic Chairs"),
                    ("Kitchen", "Kitchen"),
                    ("Decor", "Decor"),
                    ("Mattress", "Mattress"),
                    ("Kids", "Kids"),
                    ("Pots and Plants", "Pots and Plants"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
