# Generated by Django 5.2.4 on 2025-09-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0075_product_room_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="room_type",
            new_name="room_or_product_type",
        ),
    ]
