# Generated by Django 5.2.4 on 2025-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0078_wishlist_wishlistitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("img", models.ImageField(upload_to="categories/")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
