# Generated by Django 5.2.4 on 2025-10-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0080_rename_rooms_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="img",
        ),
    ]
