# Generated by Django 5.2.4 on 2025-10-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0081_remove_room_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="room_or_Product_Type",
        ),
    ]
