# Generated by Django 5.2.4 on 2025-10-03 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0082_remove_product_room_or_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="room_or_Product_Type",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="furni.room"
            ),
            preserve_default=False,
        ),
    ]
