# Generated by Django 5.2.4 on 2025-10-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0083_product_room_or_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
