# Generated by Django 5.2.4 on 2025-10-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0084_room_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
