# Generated by Django 5.2.4 on 2025-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0085_alter_room_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
