# Generated by Django 5.2.4 on 2025-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0086_categorie_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
