# Generated by Django 5.2.4 on 2025-10-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0087_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Failed", "Failed"),
                    ("Success", "Success"),
                ],
                default=1,
                max_length=40,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="razor_order_id",
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
