# Generated by Django 5.2.4 on 2025-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0088_orders_payment_status_orders_razor_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="img",
            field=models.ImageField(default=1, upload_to="testimonials/"),
            preserve_default=False,
        ),
    ]
