# Generated by Django 5.2.4 on 2025-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0089_testimonial_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="lastname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
