# Generated by Django 5.2.4 on 2025-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0090_alter_contact_lastname_alter_contact_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sub_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, default="", unique=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
