# Generated by Django 5.2.4 on 2025-10-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0091_sub_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sub_Product",
            new_name="SubProduct",
        ),
    ]
