# Generated by Django 5.2.4 on 2025-10-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0092_rename_sub_product_subproduct"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubProduct",
            new_name="RoomProductType",
        ),
    ]
