# Generated by Django 5.2.4 on 2025-10-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0094_subproducttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproducttype",
            name="Product_Type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.roomproducttype",
            ),
            preserve_default=False,
        ),
    ]
