# Generated by Django 5.2.4 on 2025-10-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0095_subproducttype_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Product_Type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.roomproducttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="Sub_Product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.subproducttype",
            ),
            preserve_default=False,
        ),
    ]
