# Generated by Django 5.2.4 on 2025-10-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furni", "0096_product_product_type_product_sub_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomproducttype",
            name="Room_Type",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="furni.room"
            ),
            preserve_default=False,
        ),
    ]
