# Generated by Django 5.2.9 on 2026-01-16 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0097_roomproducttype_room_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="Product_Type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="room_or_Product_Type",
        ),
    ]
