# Generated by Django 5.2.9 on 2026-01-11 07:59

import furni.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0097_roomproducttype_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_no",
            field=models.CharField(
                default=furni.models.generate_order_id,
                editable=False,
                max_length=50,
                unique=True,
            ),
        ),
    ]
