# Generated by Django 5.2.9 on 2026-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0098_alter_orders_order_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img3",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
