# Generated by Django 5.2.9 on 2026-01-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0098_remove_product_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Product_Type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="furni.roomproducttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="room_or_Product_Type",
            field=models.ForeignKey(
                default=11, on_delete=django.db.models.deletion.CASCADE, to="furni.room"
            ),
            preserve_default=False,
        ),
    ]
