# Generated by Django 5.2.9 on 2026-01-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0099_product_product_type_product_room_or_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="product_galleries/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="furni.product"
                    ),
                ),
            ],
        ),
    ]
