# Generated by Django 5.2.9 on 2026-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0099_alter_product_img3"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img4",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="img3",
            field=models.ImageField(default=11, upload_to="products/"),
            preserve_default=False,
        ),
    ]
