# Generated by Django 5.2.9 on 2026-01-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0100_productimagegallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimagegallery",
            name="img",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
