# Generated by Django 5.2.9 on 2026-01-16 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0099_product_product_type_product_room_or_product_type"),
        ("furni", "0100_product_img4_alter_product_img3"),
    ]

    operations = []
