# Generated by Django 5.2.9 on 2026-01-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0101_alter_productimagegallery_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img4",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimagegallery",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="furni.product",
            ),
        ),
    ]
