# Generated by Django 5.2.9 on 2026-01-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0101_merge_20260116_2125"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="img4",
        ),
        migrations.CreateModel(
            name="ProductImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="products/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="furni.product",
                    ),
                ),
            ],
        ),
    ]
