# Generated by Django 5.2.9 on 2026-01-17 11:13

from django.db import migrations


def move_images(apps, schema_editor):
    Product = apps.get_model('furni', 'Product')
    ProductImage = apps.get_model('furni', 'ProductImageGallery')

    for product in Product.objects.all():
        for field in ['img', 'img2', 'img3']:
            image = getattr(product, field)
            if image:
                ProductImage.objects.create(
                    product=product,
                    img=image
                )

class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0102_remove_product_img4_productimagegallery"),
    ]

    operations = [migrations.RunPython(move_images)]
