# Generated by Django 5.2.9 on 2026-01-19 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0103_auto_20260117_1939"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="img",
        ),
        migrations.RemoveField(
            model_name="product",
            name="img2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="img3",
        ),
    ]
