# Generated by Django 5.2.9 on 2026-01-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furni", "0104_remove_product_img_remove_product_img2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions_depth_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions_height_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions_width_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
