services:
  module_app:
    build: .
<<<<<<< HEAD
    ports:
      - 8000:8000
    env_file:
      - .env
=======
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - /var/www/myproject/static:/staticfiles
      - /var/www/myproject/media:/media
    restart: unless-stopped
    
>>>>>>> main
