from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name = "home"),
    path('shop', views.shop, name = "shop"),
    path('about', views.about, name = 'aboutus'),
    path('contact', views.contact, name = 'contactus'),
    path('services', views.services, name = 'services'),
    path('shop/<int:cat_id>/', views.category, name = "category"),
    path('leadership', views.leaders, name="leaders"),
    path('carrers',views.carrers, name="carrers"),
    path('register',views.registerpage, name="registerpage"),
    path('login',views.loginpage, name="loginpage"),
    path('logout',views.logoutrequest, name="logoutpage"),
    #path('profile',views.profilepage, name="profilepage"),
    path('shop/<int:cat_id>/product/<int:prod_id>', views.product, name = "product"),
    path('cart', views.view_cart, name = "cart"),
    path('add/<int:product_id>/<int:qty>/', views.add_to_cart, name = "add_to_cart" ),
    path('buy/<int:product_id>/<int:qty>/', views.buynow, name = "buy_now"),
    path('remove/<int:cart_item_id>/', views.delete_from_cart, name = "delete_from_cart"),
    path('update/<int:cart_item_id>/<int:qty>/', views.update_cart, name = "update_cart"),
    path('checkout', views.checkout, name = 'checkout'),
    path('profile', views.profile, name="profile"),
    path('edit_account', views.edit_account, name="edit_account"),
    path('edit_password', views.edit_password, name="edit_password"),
    path('edit_email', views.edit_email, name="edit_email"),
    path('edit_name', views.edit_name, name="edit_name"),
    path("password_success", views.passwordsuccesspage, name="passwordsuccesspage"),
    path("email_success", views.emailsuccesspage, name="emailsuccesspage"),
    path("name_success", views.namesuccesspage, name="namesuccesspage"),
    path('orders', views.orders, name="orders"),
    path('view_order/<int:order_id>/', views.indiv_orders, name="view_order"),
    path('view_single_order/<str:order_no>/<str:email_id>/', views.single_order, name="view_single_order"),
    path('return/<int:order_id>/<int:order_item_id>/', views.returns, name="return"),
    path('address', views.address, name="address"),
    path('delete_address/<int:address_id>/', views.delete_address, name="delete_address"),
    path('add_address', views.add_address, name="add_address"),
    path('edit_address/<int:address_id>/', views.edit_address, name="edit_address"),
]